name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 0.3.0
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^6.0.0
  sqflite: ^1.3.0
  path: ^1.7.0
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter
